name: dart_json
description: A library intended to bring manual JSON serialization to the Dart projects of all scales.
version: 2.0.1
repository: https://github.com/npu3pak/dart-lib-json

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4
  lints: ^2.0.1
